### ISSUE TITLE
Content Intake Matrix

### ISSUE THREAD

**Issue by heyitsolivia** [washington-leadership-academy/wla#26]
**Wireframes**
https://www.dropbox.com/sh/zxviwag6immj7gy/AABXDgqq3vaRMsHCw9-Ukn_ja?dl=0

**Component Comps**
https://www.dropbox.com/s/79jiguvaazizik9/Component%20Character%20Counts%203-14-16-1.jpg?dl=0

**Content Intake Matrix**
https://docs.google.com/spreadsheets/d/1cwIzaRJr9K2TObx5MwLhd0b4LbRWm5vibogi4SvFUo4/edit?usp=sharing

**Task List**
- [x] Homepage Copy
- [x] About Us Page Copy
- [x] Founding Story Page Copy
- [x] Our Approach Page Copy
- [x] Team Page Copy
- [ ] Academics Page Copy
- [ ] Student Life Page Copy
- [ ] Donate Page Copy
- [ ] How to Enroll Page Copy

**Due Date** - April 19th

**Comment by alxmrtnz** [comment]
![screen shot 2016-03-16 at 5 28 51 pm](https://cloud.githubusercontent.com/assets/1167326/13829328/d17e4bd6-eb9c-11e5-970b-f117ffc6e2b9.png)

**Comment by awarehouse** [comment]
Hey @stacykane and @nataliegould. This will serve as our Content Intake Github ticket. I will add new pages that will need copy into the "Content Intake Matrix" google Doc as their digital comps are finished, and then inform you that there is a new page up. Please feel free to ask any questions that you come across. Once you are finished with a page, you can check off the box , comment back to me, I will revise the document, and then reassign to you. 

Tips:
- Use the Wireframes to match up the sections on each page
- Use the Component Comps to remember what the design comp will look like

**Comment by awarehouse** [comment]
@stacykane @nataliegould Please have the first 5 pages finished by 4/6. Thank you!
