### ISSUE TITLE
Set up developer environment

### ISSUE THREAD

**Issue by heyitsolivia** [washington-leadership-academy/wla#27]
**Tasks**
- [x] Set up gulp for sass + js
- [x] Set up Node Squarespace Server
- [x] Set up Foundation
- [x] Update documentation
